name: Jest Testing

on:
  - push
  - pull_request

jobs:
  test:
    name: Jest Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js v16 Environment
      uses: actions/setup-node@v3.1.0
      with:
        node-version: 16
        cache: 'npm'
        cache-directory-path: package.json

    - name: Install & Run Node dependencies
      run: |
        npm i -g jest
        jest --verbose
